apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-usage-config
  namespace: perses-dev
data:
  config.yaml: |
    metric_collector:
      enable: true
      period: "1d"
      http_client:
        url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    labels_collectors:
      - enable: true
        period: "1d"
        concurrency: 5
        prometheus_client:
          url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    perses_collector:
      enable: true
      period: "1d"
      perses_client:
        url: "http://perses-sample.perses-dev.svc.cluster.local:8080"
    # rules_collectors not enabled — this repo deploys dashboards only
